### ISSUE TITLE
R-Ladies website: Table of all Chapters does not include African countries and their chapters

### ISSUE THREAD

**Issue by sndaba** [rladies/rladies.github.io#134]
Hi, I noticed that the African countries and their chapters are not included in the Table of all Chapters list, except for South Africa.
I hope they can be added so that they can be represented as well.

**Comment by drmowinckels** [comment]
Hi!

Thank you for picking that up, and letting us know. They are in the map, meaning the data should be there. I'll dig into the table code and see if I can figure out what is up.

**Comment by sndaba** [comment]
Hi,

Great....Thank you so much.

**Comment by drmowinckels** [comment]
no, all thanks is to you! I cant believe I missed such a thing!
