### ISSUE TITLE
Press - it have been several interview from the RConsortium to R-Ladies

### ISSUE THREAD

**Issue by yabellini** [rladies/rladies.github.io#137]
We should list those on our wbpage:

https://www.r-consortium.org/blog/2023/02/28/happy-23rd-birthday-r
https://www.r-consortium.org/blog/2023/02/09/r-ladies-vitoria-use-of-r-maternal-and-child-health-brazil
https://www.r-consortium.org/blog/2022/12/12/learning-the-fundamentals-of-r-workshop-with-r-ladies-gaborone-and-botswana-r-user-group
https://www.r-consortium.org/blog/2022/08/23/r-ladies-taipei-hopes-to-host-hybrid-events-in-the-future
https://www.r-consortium.org/blog/2022/07/26/r-ladies-philly-is-making-a-difference-with-its-annual-datathon-focused-on-local-issues
https://www.r-consortium.org/blog/2022/07/14/r-ladies-santa-rosa-leading-with-other-r-communities-in-latin-america-to-create-more-accessibility
https://www.r-consortium.org/blog/2022/07/07/r-ladies-cuernacava-partners-with-biotechnology-institute
https://www.r-consortium.org/blog/2022/07/05/virtual-events-opened-new-horizons-for-r-ladies-dallas
https://www.r-consortium.org/blog/2022/06/06/r-ladies-cotonou-talks-about-running-a-group-in-a-developing-country
https://www.r-consortium.org/blog/2022/01/26/r-ladies-galapagos-chapter-on-collaborations-challenges-and-opportunities-during-the-pandemic
https://www.r-consortium.org/blog/2021/12/22/r-ladies-lagos-on-data-visualization-and-hybrid-events
https://www.r-consortium.org/blog/2021/11/09/chiles-r-ladies-group-is-open-and-inclusive
https://www.r-consortium.org/blog/2021/07/20/latin-r-talks-about-the-trials-of-starting-a-conference-in-latin-america
https://www.r-consortium.org/blog/2021/07/20/latinr-explains-how-to-create-a-high-quality-conference-in-the-southern-hemisphere
https://www.r-consortium.org/blog/2021/06/24/working-with-databases-in-r-video-presentation-from-nairobir-and-r-ladies-nairobi
https://www.r-consortium.org/blog/2021/05/27/r-ladies-philly-building-our-online-community-during-the-pandemic
https://www.r-consortium.org/blog/2021/05/14/checking-in-with-r-ladies-taipei
https://www.r-consortium.org/blog/2020/07/07/latin-american-communities-and-organizations-at-user2020

**Comment by drmowinckels** [comment]
Great!

We should for sure include them.

These go under the "press" content. 
https://github.com/rladies/rladies.github.io/tree/main/content/press

One md per link :) 

If anyone has the time before me, go ahead. Else I'll try getting to it over the weekend
