### ISSUE TITLE
breaking change in renv

### ISSUE THREAD

**Issue by drmowinckels** [rladies/rladies.github.io#175]
There is a breaking change in renv, and its making the website not build :( 
I'm having issues with my mac's developer tools, so I cant get this fixed before I get that sorted.

If @cosimameyer or @SoyAndrea feel adventurous, I think the main job is really to update renv and all packages to the latest and hope that fixes it all. 
Here's some information on renv and continuous integration (which GitHub actions are)
https://rstudio.github.io/renv/articles/ci.html

I can pick this up on Friday, probably, if I manage to fix my computer

**Comment by drmowinckels** [comment]
Others struggling with the same:

- https://github.com/r-hub/cransays/issues/53#issuecomment-1631504290
- https://community.rstudio.com/t/r-cmd-check-on-github-actions-failing-suddenly-with-missing-renv-version/169670

**Comment by cosimameyer** [comment]
Just googled a bit in the issues and this could be the solution: https://github.com/r-lib/actions/issues/741
