### ISSUE TITLE
Add end date for Cristin's entry

### ISSUE THREAD

**Issue by cosimameyer** [rladies/rladies.github.io#186]
There are some display problems with the end date (it's missing) for [Cristin's entry](https://rladies.org/about-us/global-team/) (see screenshot). If you tell me the end date, I'll quickly fix it in a PR :) 

<img width="116" alt="image" src="https://github.com/rladies/rladies.github.io/assets/7782895/d7f2f736-5186-4ea8-866c-94424847b305">

**Comment by drmowinckels** [comment]
Lets set the end-date at December 2022 .
