### ISSUE TITLE
Some images for the Global Team don’t display correctly

### ISSUE THREAD

**Issue by cosimameyer** [rladies/rladies.github.io#193]
Some images for the Global Team don’t display correctly. I checked with different browsers on my mobile but it’s always the same. I thought it might be caching but there’s a pattern: it’s the new entries. Does this also happen to you, @rladies/website?
![IMG_2849](https://github.com/rladies/rladies.github.io/assets/7782895/e8e9ad14-e0d6-4dd7-9395-1032ee7bc5b9)

**Comment by cosimameyer** [comment]
I built the site locally and all looks good (but the problem persists when using the online version - also after clearing the cache): 
<img width="706" alt="Screenshot 2023-07-30 at 07 17 37" src="https://github.com/rladies/rladies.github.io/assets/7782895/31a418cf-56ac-4aa0-972f-c136cb5514e5">

**Comment by drmowinckels** [comment]
I see it too. Its so strange, the previews look just fine.

**Comment by drmowinckels** [comment]
I think I found it. I recently changed the config.toml to hugo.toml, as per new hugo way of working. and misspelled the production version to `hugos.toml` so the site base URL was wrong. PR #195 shoudl hopefully fix this.
