### ISSUE TITLE
community slack form

### ISSUE THREAD

**Issue by drmowinckels** [rladies/rladies.github.io#208]
heroku not working. new workflow not ready yet, but the form for it can be used. so change URL.

- [x] https://github.com/rladies/rladies.github.io/blob/main/content/about-us/involved/index.en.md?plain=1#L19 to new url
- [x] make pretty url with redirect like directory form

**Comment by drmowinckels** [comment]
I thought we could do this together, so that you can see how I make the redirects to forms (so we can have prettier urls).

**Comment by cosimameyer** [comment]
That sounds fantastic! I’ll be on holidays starting September 8 but flexible before. Ideally some time after 6 PM CEST 😊

**Comment by SoyAndrea** [comment]
Hi team 💜! I can meet on Wednesdays at the time you need.

**Comment by drmowinckels** [comment]
Hi! Sorry for taking so long. My schedule since my holidays have been tough. @cosimameyer when will you be back from holidays?

**Comment by cosimameyer** [comment]
On September 22 ☺️

**Comment by drmowinckels** [comment]
ok. I'm taking so long with things these days :) 

Here's a poll to find time to meet once Cosima is back :) 
https://www.when2meet.com/?21297237-AGsUW

**Comment by cosimameyer** [comment]
Sorry for being so slow here - I didn't see it before and just picked a time slot ☺️
It looks like we found a good slot for all of us 🥳

<img width="302" alt="image" src="https://github.com/rladies/rladies.github.io/assets/7782895/db005d1d-00a3-47bd-b6fc-1a9ae5b0d221">

**Comment by drmowinckels** [comment]
You should have received an invite in the mail :)

**Comment by drmowinckels** [comment]
the url to the form:
https://airtable.com/appJZFYABfCIdPYMR/shrReqdN8fhuXGY3P

**Comment by SoyAndrea** [comment]
I created this PR https://github.com/rladies/rladies.github.io/pull/258 :)

**Comment by drmowinckels** [comment]
thank you @SoyAndrea ! Great work!
